#------ Imported config must be quite empty to avoid loosing time from a/r -----#
server:
  port: 9000
spring:
  application:
    name: ms-course-mgmt
  datasource:
    url: jdbc:mysql://mscoursemgmtdb:3306/coursemgmtdb?useUnicode=true&characterEncoding=utf8mb4
    username: ${MYSQL_COURSE_DB_USERNAME}
    password: ${MYSQL_COURSE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msdiscovery:8761/eureka/