#------ Imported config must be quite empty to avoid loosing time from a/r -----#
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8090
spring:
  application:
    name: ms-identity
  datasource:
    url: jdbc:mysql://msidentitydb:3306/identitydb?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msdiscovery:8761/eureka/