#------ Configuration DEV pour ms-notification -----#
server:
  port: 9010

spring:
  application:
    name: ms-notification
  profiles:
    active: mock  #mock profile for development

  data:
    mongodb:
      uri: ${MONGODB_URI}

  # Basic SMTP config (unused in mock mode)
  mail:
    host: localhost
    port: 25
    properties:
      mail.transport.protocol: smtp

# Notification settings - Mock mode for development
notification:
  email:
    enabled: true     # Active service
    mock: true        # Mock mode (only logs)
    from: noreply@kundapp.com
    templates:
      enrollment: enrollment
      cancellation: cancellation
      modification: modification
      session-cancelled: session-cancelled
      session-modified: session-modified
      session-completed: session-completed

# Resilience4j configuration
resilience4j:
  retry:
    instances:
      email-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.lang.Exception
  circuitbreaker:
    instances:
      email-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 5s

# Eureka registration - Utilise variable d'environnement
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

# Logging configuration
logging:
  level:
    jroullet.msnotification: DEBUG
    io.github.resilience4j: DEBUG
    org.springframework.mail: DEBUG