server:
  port: 8080
spring:
  application:
    name: ms-webapp
  datasource:
    url: jdbc:mysql://msidentitydb:3306/identitydb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    #    Allows tables creation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msdiscovery:8761/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, refresh