server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
spring:
  spring:
    web:
      locale: fr_FR
    thymeleaf:
      encoding: UTF-8
  application:
    name: ms-webapp
#  datasource:
#    url: jdbc:mysql://msidentitydb:3306/identitydb
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    #    Allows tables creation
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#  sql:
#    init:
#      mode: never
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msdiscovery:8761/eureka/
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, refresh